<?php

error_reporting(E_ALL);
ini_set('display_errors', '1');

function datapress_menu() { 
//  $items['datapress/node/%node/json'] = array(
//    'page callback' => 'datapress_json_endpoint',
//    'page arguments' => array(1),
//    'access arguments' => array('access content'),
//  );
  $items['datapress/node/type/%/json'] = array(
    'page callback' => 'datapress_nodes_by_type',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );
  $items['datapress/user/role/%/json'] = array(
    'page callback' => 'datapress_users_by_role',
    'page arguments' => array(3),
    'access arguments' => array('access content'),
  );
  return $items;
}

function datapress_nodes_by_type($type) {
  $ret = array();
  $ret["type"] = $type;
  $ret["items"] = array();
  $query = new EntityFieldQuery();
  $nodes = $query->entityCondition('entity_type', 'node')
                 ->propertyCondition('type', $type)
                 ->propertyCondition('status', 1)
                 ->execute();
  $ret["nodes"] = $nodes;
  if (!empty($nodes["node"])) {
    foreach ($nodes["node"] as $key => $node) {
      $node = node_load($key);
      $items = datapress_node_export($node);
      foreach ($items as $item) {
        array_push($ret["items"], $item);
      }
    }
  }
  drupal_json_output($ret);
}

function datapress_users_by_role($roleName) {
  $ret = array();
  $ret["items"] = array();
  $role = user_role_load_by_name($roleName);
  if ($role) {
    $result = db_select('users_roles', 'ur')
               ->fields('ur', array('uid'))
               ->condition('rid', $role->rid)
               ->execute();
    
    foreach($result as $record) {
      $uids[] = $record->uid;
    }
  
    $query = new EntityFieldQuery();
    $users = $query->entityCondition('entity_type', 'user')
                   ->entityCondition('entity_id', $uids, 'IN')
                   ->propertyCondition('status', 1)
                   ->execute();
  
    if (!empty($users["user"])) {
      foreach ($users["user"] as $key => $user) {
        $user = user_load($key);
        $items = datapress_user_export($user);
        foreach ($items as $item) {
          array_push($ret["items"], $item);
        }
      }
    }
  }
  drupal_json_output($ret);
}

function datapress_node_export($node) {
  $items = array();
  $ret = array();
  $ret['id'] = $node->nid;
  $ret['nid'] = $node->nid;
  $ret['type'] = $node->type;
  $ret['label'] = $node->title;
  $ret['title'] = $node->title;
  $ret['creator_picure'] = $node->picture;
  $ret['creator'] = $node->name;
  $ret['created'] = $node->created;
  $ret['body'] = $node->body["und"][0]["value"];
  $ret['summary'] = $node->body["und"][0]["summary"];
  $ret['fullbody'] = $node->body;
  //$ret['all'] = $node;

  $needle = "field_";
  foreach ($node as $key => $value) {
    // StartsWith
    if (!strncmp($key, $needle, strlen($needle))) {
      $custom = datapress_get_custom_field_value($value);
      if ($custom != null) {
        $prefix = substr($key, 6);
        $ret["custom-" . $prefix] = $custom["main"];
        foreach ($custom["additional"] as $additional) {
          array_push($items, $additional);
        }
      }
    }
  }
  array_push($items, $ret);
  return $items;
}

function datapress_user_export($user) {
  $items = array();
  $ret = array();
  $ret['id'] = $user->uid;
  $ret['uid'] = $user->uid;
  $ret['label'] = $user->name;
  $ret['name'] = $user->name;
  $ret['type'] = "User";
  if (isset($user->picture)) {
    if (isset($user->picture->uri)) {
      $ret['picture-uri'] = $user->picture->uri;
      $ret['picture-filename'] = $user->picture->filename;
    }
  }

  $ret['roles'] = array();
  foreach ($user->roles as $id => $name) {
    array_push($ret['roles'], $name);
  }

  $needle = "field_";
  foreach ($user as $key => $value) {
    // StartsWith
    if (!strncmp($key, $needle, strlen($needle))) {
      $custom = datapress_get_custom_field_value($value);
      if ($custom != null) {
        $prefix = substr($key, 6);
        $ret["custom-$prefix"] = $custom["main"];
        foreach ($custom["additional"] as $additional) {
          array_push($items, $additional);
        }
      }
    }
  }
  array_push($items, $ret);
  return $items;
}

function datapress_get_custom_field_value($value) {
  $ret = array();
  $additional = array();
  $language = "und";
  if (isset($value[$language])) {
    foreach($value[$language] as $item) {
      $x = array();
      if (isset($item["value"])) {
        array_push($ret, $item["value"]);
      } elseif (isset($item["filename"])) {
        $fname = $item["filename"];
        if (isset($item["uri"])) {
          // Override with URI if possible
          if (!(strpos($item["uri"], "//") === false)) {
            $fname  = substr($item["uri"], strpos($item["uri"], "//") + 2);
          }
        }
        array_push($ret, $fname);
      } elseif (isset($item["uid"])) {
        $user = user_load($item["uid"]);
        $x["name"] = $user->name;
        $x["uid"] = $user->uid;
        array_push($ret, $x);
      } elseif (isset($item["nid"])) {
        $node = node_load($item["nid"]);
        $x["name"] = $node->title;
        $x["nid"] = $node->nid;
        array_push($ret, $x);
      }
    }
  }
  
  if (sizeof($ret) == 1) {
    if (strlen($ret[0]) == 0) {
      return null;
    } else {
      $custom = array();
      $custom["main"] = $ret[0];
      $custom["additional"] = $additional;
      return $custom;
    }
  } elseif (sizeof($ret) == 0) {
    return null;
  } else {
     $custom = array();
     $custom["main"] = array_values($ret);
     $custom["additional"] = $additional;
     return $custom;
  }
}

