<?php

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function datapress_help($path, $arg) {
  switch ($path) {
    case "admin/help#datapress":
      return '<p>' . t("Helps facet objects.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function datapress_block_info() {
  $blocks['current_posts'] = array(
    'info' => t('Datapress'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
 * Displays the datapress block.
 */
function datapress_block_view($delta = '') {
  switch($delta){
    case 'current_posts':
      $block['subject'] = t('Current posts');
      if(user_access('access content')){
        //Use our custom function to retrieve data.
        $result = datapress_block_contents();
        //Array to contain items for the block to render.
        $items = array();
        //Iterate over the resultset and format as links.
        foreach ($result as $node){
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          ); 
        }
        
        if (empty($items)) { //No content in the last week.
          $block['content'] = t('No posts available.');  
        } 
      else {
        //Pass data through theme function.
        $block['content'] = theme('item_list', array(
          'items' => $items));
        }
      }
  }
  return $block;
}

/**
 * Datapress factet function
 * 
 * @return 
 *   The body of the facets for this page
 */
function datapress_block_contents() {
  return "FOO";
} 
