<?php

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function datapress_help($path, $arg) {
  switch ($path) {
    case "admin/help#datapress":
      return '<p>' . t("Helps facet objects.") . '</p>';
      break;
  }
}

/**
 * Implements hook_block_info().
 */
function datapress_block_info() {
  $blocks['datapress'] = array(
    'info' => t('Datapress'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}


/**
 * Datapress factet function
 * 
 * @return 
 *   The body of the facets for this page
 */
function datapress_facets() {
  return array();
} 

/**
 * Displays the datapress block.
 */
function datapress_block_view($delta = '') {
  switch($delta) {
    case 'current_posts':
      $block['subject'] = t('Fiter Items');
      if (user_access('access content')) {
        //Use our custom function to retrieve data.

        $facets = datapress_facets();

        if (empty($facets)) { //No content in the last week.
          $block['content'] = t('No filters available.');  
        } 

        ////Iterate over the resultset and format as links.
        //foreach ($result as $node){
        //  $items[] = array(
        //    'data' => l($node->title, 'node/' . $node->nid),
        //  ); 
        //}
      }
  }
  return $block;
}

